<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Aether_NBody_Simulation\SimulationCommand.cs" Link="SimulationCommand.cs" />
    <Compile Include="..\Aether_NBody_Simulation\ControlPipeServer.cs" Link="ControlPipeServer.cs" />
  </ItemGroup>
</Project>
